dist: bionic
language: cpp
compiler: gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-9 g++-9
script: 
  - cd test
  - make CXX=g++-9 bmi2
  - make CXX=g++-9 avx512
  - make CXX=g++-9 test
# This really should finish in less than 2 minutes - otherwise something's wrong
  - timeout 120 ./libmorton_test 128
